name: Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: cli/gh-action@v2
        with:
          version: latest

      - name: Approve and merge Dependabot PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch
